#ifndef lexer_matrix_h
#define lexer_matrix_h
/* Generated by mgclex, the simplest lexer-generator in the northeast */
typedef enum TKSymbol {
TK_NUM,
 TK_LCURLY, TK_RCURLY,TK_LSQB,TK_RSQB,TK_COLON,
TK_COMMA,TK_TRUE,TK_FALSE,TK_NULL,TK_STRING,
 TK_EOI
} TKSymbol;

extern const char* tokenStr[];
extern const int matrix[27][256]; // Assuming these are arrays/global variables
extern const int accept[];

#endif